# Setup python and run the main program

name: Python

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.12', '3.13']

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Dependencies
      run: pip install -r requirements.txt

    - name: Newcomb
      env:
        PYTHONPATH: .
      run: |
        python main.py CDT newcomb --verbose
        python main.py EDT newcomb --verbose
        python main.py TDT newcomb --verbose
        python main.py UDT1.1 newcomb --verbose

    - name: Red Room Blue Room
      env:
        PYTHONPATH: .
      run: |
        python main.py CDT redroom
        python main.py CDT blueroom
        python main.py EDT redroom
        python main.py EDT blueroom
        python main.py TDT redroom
        python main.py TDT blueroom
        python main.py UDT1.1 redroom
        python main.py UDT1.1 blueroom
